- name: Playing with files
  become: true
  hosts: all
  tasks:
    - name: Create multiple files by using with_items
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        mode: "{{ item.mode }}"
        state: touch
      with_items:
        - { path: /home/ubuntu/1.txt, owner: ubuntu, mode: 0644}
        - { path: /home/ubuntu/2.txt, owner: ubuntu, mode: 0644}
      register: withitemvariable

    - name: Create mutltiple file by using loops
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        state: touch
      loop:
        - { path: /home/ubuntu/3.txt, owner: ubuntu}
        - { path: /home/ubuntu/4.txt, owner: ubuntu}
      register: loopvariable

    - name: Register with items 
      command: echo {{ item }}
      with_items:
        - [4, 5]
      register: withitemvariable
    
    - name: Register with loop 
      command: echo {{ item }}
      loop: "{{ [4, 5] | flatten(1)}}"
      register: withloopvariable